# Generated by Django 6.0.2 on 2026-04-24 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aggregators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_in_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight_out_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stage', models.CharField(choices=[('received', 'Received'), ('qc', 'QC Check'), ('processing', 'Processing'), ('done', 'Completed')], default='received', max_length=20)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user_credit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recycler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('total_kg_processed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actual_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('incoming', 'Incoming'), ('received', 'Received'), ('rejected', 'Rejected')], default='scheduled', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='aggregators.pickupjob')),
            ],
        ),
    ]
