# Generated by Django 6.0.2 on 2026-04-24 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recyclers', '0001_initial'),
        ('waste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialinventory',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.material'),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.material'),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recyclers.incomingshipment'),
        ),
        migrations.AddField(
            model_name='recycler',
            name='accepted_materials',
            field=models.ManyToManyField(blank=True, to='waste.material'),
        ),
        migrations.AddField(
            model_name='recycler',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='recycler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='recyclers.recycler'),
        ),
        migrations.AddField(
            model_name='materialinventory',
            name='recycler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='recyclers.recycler'),
        ),
        migrations.AddField(
            model_name='incomingshipment',
            name='recycler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='recyclers.recycler'),
        ),
        migrations.AlterUniqueTogether(
            name='materialinventory',
            unique_together={('recycler', 'material')},
        ),
    ]
