# Generated by Django 6.0.2 on 2026-04-24 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(max_length=10)),
                ('points_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cash_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='submissions/')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('preferred_pickup_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ml_processing', 'ML Processing'), ('ml_verified', 'ML Verified'), ('manual_review', 'Manual Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('aggregator_assigned', 'Aggregator Assigned'), ('collected', 'Collected'), ('recycler_received', 'Recycler Received'), ('completed', 'Completed')], default='pending', max_length=30)),
                ('ml_confidence', models.FloatField(blank=True, null=True)),
                ('ml_verified', models.BooleanField(default=False)),
                ('manually_reviewed', models.BooleanField(default=False)),
                ('base_points', models.PositiveIntegerField(default=0)),
                ('tier_bonus_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('cash_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste.material')),
                ('ml_predicted_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_predictions', to='waste.material')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('raw_output', models.JSONField()),
                ('predicted_label', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('processing_time_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='waste.wastesubmission')),
            ],
        ),
    ]
