# Generated by Django 6.0.2 on 2026-04-24 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aggregators', '0001_initial'),
        ('waste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='accepted_materials',
            field=models.ManyToManyField(blank=True, to='waste.material'),
        ),
        migrations.AddField(
            model_name='aggregator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregator_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aggregatorcommission',
            name='aggregator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='aggregators.aggregator'),
        ),
        migrations.AddField(
            model_name='pickupjob',
            name='aggregator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='aggregators.aggregator'),
        ),
        migrations.AddField(
            model_name='pickupjob',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_job', to='waste.wastesubmission'),
        ),
        migrations.AddField(
            model_name='aggregatorcommission',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aggregators.pickupjob'),
        ),
    ]
